# Generated by Django 3.2.16 on 2025-03-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250313_1753'),
        ('posts', '0004_auto_20250308_2241'),
    ]

    operations = [
    ]
